export const initialCategories = [
    {
      id: 1,
      categoryName: "frequently used",
      iconName: "FrequentlyUsedIcon",
    },
    {
      id: 2,
      categoryName: "smileys and people",
      iconName: "SmileysAndPeopleIcon",
    },
    {
      id: 3,
      categoryName: "animals and nature",
      iconName: "AnimalsAndNatureIcon",
    },
    {
      id: 4,
      categoryName: "food and drink",
      iconName: "FoodAndDrinkIcon",
    },
    {
      id: 5,
      categoryName: "activities",
      iconName: "ActivitiesIcon",
    },
    {
      id: 6,
      categoryName: "travel and places",
      iconName: "TravelAndPlacesIcon",
    },
    {
      id: 7,
      categoryName: "objects",
      iconName: "ObjectsIcon",
    },
    {
      id: 8,
      categoryName: "symbols",
      iconName: "SymbolsIcon",
    },
    {
      id: 9,
      categoryName: "flags",
      iconName: "FlagsIcon",
    },
  ];
  
  export const initialfrequentlyUsed = [
    {
      name: "face with tears of joy",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128514;"],
      unicode: ["U+1F602"],
    },
    {
      name: "heavy black heart ≊ red heart",
      category: "smileys and people",
      group: "emotion",
      htmlCode: ["&#10084;"],
      unicode: ["U+2764"],
    },
    {
      name: "smiling face with heart-shaped eyes ≊ smiling face with heart-eyes",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128525;"],
      unicode: ["U+1F60D"],
    },
    {
      name: "unamused face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128530;"],
      unicode: ["U+1F612"],
    },
    {
      name: "ok hand sign ≊ ok hand",
      category: "smileys and people",
      group: "body",
      htmlCode: ["&#128076;"],
      unicode: ["U+1F44C"],
    },
    {
      name: "white smiling face ≊ smiling face",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#9786;"],
      unicode: ["U+263A"],
    },
    {
      name: "smiling face with smiling eyes",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128522;"],
      unicode: ["U+1F60A"],
    },
    {
      name: "face throwing a kiss",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128536;"],
      unicode: ["U+1F618"],
    },
    {
      name: "loudly crying face",
      category: "smileys and people",
      group: "face negative",
      htmlCode: ["&#128557;"],
      unicode: ["U+1F62D"],
    },
    {
      name: "weary face",
      category: "smileys and people",
      group: "face negative",
      htmlCode: ["&#128553;"],
      unicode: ["U+1F629"],
    },
    {
      name: "two hearts",
      category: "smileys and people",
      group: "emotion",
      htmlCode: ["&#128149;"],
      unicode: ["U+1F495"],
    },
    {
      name: "pensive face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128532;"],
      unicode: ["U+1F614"],
    },
    {
      name: "smirking face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128527;"],
      unicode: ["U+1F60F"],
    },
    {
      name: "grinning face with smiling eyes",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128513;"],
      unicode: ["U+1F601"],
    },
    {
      name: "flushed face",
      category: "smileys and people",
      group: "face negative",
      htmlCode: ["&#128563;"],
      unicode: ["U+1F633"],
    },
    {
      name: "thumbs up sign ≊ thumbs up",
      category: "smileys and people",
      group: "body",
      htmlCode: ["&#128077;"],
      unicode: ["U+1F44D"],
    },
    {
      name: "victory hand",
      category: "smileys and people",
      group: "body",
      htmlCode: ["&#9996;"],
      unicode: ["U+270C"],
    },
    {
      name: "winking face",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128521;"],
      unicode: ["U+1F609"],
    },
    {
      name: "relieved face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128524;"],
      unicode: ["U+1F60C"],
    },
    {
      name: "information desk person ≊ person tipping hand",
      category: "smileys and people",
      group: "person gesture",
      htmlCode: ["&#128129;"],
      unicode: ["U+1F481"],
    },
    {
      name: "see-no-evil monkey ≊ see-no-evil",
      category: "smileys and people",
      group: "monkey face",
      htmlCode: ["&#128584;"],
      unicode: ["U+1F648"],
    },
    {
      name: "smiling face with sunglasses",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128526;"],
      unicode: ["U+1F60E"],
    },
    {
      name: "multiple musical notes ≊ musical notes",
      category: "objects",
      group: "objects",
      htmlCode: ["&#127926;"],
      unicode: ["U+1F3B6"],
    },
    {
      name: "eyes",
      category: "smileys and people",
      group: "body",
      htmlCode: ["&#128064;"],
      unicode: ["U+1F440"],
    },
    {
      name: "expressionless face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128529;"],
      unicode: ["U+1F611"],
    },
    {
      name: "sleeping face",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128564;"],
      unicode: ["U+1F634"],
    },
    {
      name: "smiling face with open mouth and smiling eyes ≊ smiling face with open mouth ",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128516;"],
      unicode: ["U+1F604"],
    },
    {
      name: "face with stuck-out tongue and winking eye ≊ face with stuck-out tongue ",
      category: "smileys and people",
      group: "face neutral",
      htmlCode: ["&#128540;"],
      unicode: ["U+1F61C"],
    },
    {
      name: "face savouring delicious food",
      category: "smileys and people",
      group: "face positive",
      htmlCode: ["&#128523;"],
      unicode: ["U+1F60B"],
    },
    {
      name: "clapping hands sign ≊ clapping hands",
      category: "smileys and people",
      group: "body",
      htmlCode: ["&#128079;"],
      unicode: ["U+1F44F"],
    },
  ];